
# springdoc-openapi configuration
# To get help follow the link to get more information
# https://doc.xiaominfo.com/docs/quick-start
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        - group: 'default'
          paths-to-match: '/**'
#         Scan all your controller packages.
          packages-to-scan: 'com.asaka.swaggerhello.controller'

map:
    data:
         name: 战鹰
         age: 3

# 日志配置
# 日志配置
logging:
    # 日志级别
    level:
        root: info
    file:
        # 日志文件名格式
        name: ./logs/${spring.application.name}.log
    pattern:
        # 日志记录格式[组件名称] [时间戳] [日志级别] [类名.方法名] [消息文本]
        file: H %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    logback:
        rolling-policy:
            # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
            file-name-pattern: ./logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
            # 最大日志文件大小(默认为10MB，这里为了测试归档，暂时设置为2KB)
            max-file-size: 2KB
            # 要保留的日志备份的总大小(默认为0B)
            total-size-cap: 1GB
            # 7天内的日志文件都会被保留
            max-history: 7
